# Generated by Django 4.2.23 on 2025-06-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0002_remove_car_series_alter_car_color_alter_car_millage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date_from",
            field=models.DateField(verbose_name="rent from date (inclusive)"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="date_to",
            field=models.DateField(verbose_name="rent to date (inclusive)"),
        ),
    ]
