# Generated by Django 4.2.23 on 2025-06-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0003_alter_booking_date_from_alter_booking_date_to"),
    ]

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("completed", models.BooleanField(default=False)),
            ],
        ),
    ]
