# Generated by Django 4.2.23 on 2025-06-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0004_todo"),
    ]

    operations = [
        migrations.DeleteModel(name="Todo",),
        migrations.AlterField(
            model_name="car",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("white", "White"),
                    ("black", "Black"),
                    ("blue", "Blue"),
                    ("red", "Red"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
